const theme = {
  name: 'light-theme',
  colors: {
    primaryA: '#000000',
    primaryB: '#FFFFFF',
    primary: '#000000',
    primary50: '#F6F6F6',
    primary100: '#EEEEEE',
    primary200: '#E2E2E2',
    primary300: '#CBCBCB',
    primary400: '#AFAFAF',
    primary500: '#757575',
    primary600: '#545454',
    primary700: '#333333',
    accent: '#276EF1',
    accent50: '#EFF3FE',
    accent100: '#D4E2FC',
    accent200: '#A0BFF8',
    accent300: '#5B91F5',
    accent400: '#276EF1',
    accent500: '#1E54B7',
    accent600: '#174291',
    accent700: '#102C60',
    negative: '#E11900',
    negative50: '#FFEFED',
    negative100: '#FED7D2',
    negative200: '#F1998E',
    negative300: '#E85C4A',
    negative400: '#E11900',
    negative500: '#AB1300',
    negative600: '#870F00',
    negative700: '#5A0A00',
    warning: '#FFC043',
    warning50: '#FFFAF0',
    warning100: '#FFF2D9',
    warning200: '#FFE3AC',
    warning300: '#FFCF70',
    warning400: '#FFC043',
    warning500: '#BC8B2C',
    warning600: '#997328',
    warning700: '#674D1B',
    positive: '#05944F',
    positive50: '#E6F2ED',
    positive100: '#ADDEC9',
    positive200: '#66D19E',
    positive300: '#06C167',
    positive400: '#05944F',
    positive500: '#03703C',
    positive600: '#03582F',
    positive700: '#10462D',
    white: '#FFFFFF',
    black: '#000000',
    mono100: '#FFFFFF',
    mono200: '#F6F6F6',
    mono300: '#EEEEEE',
    mono400: '#E2E2E2',
    mono500: '#CBCBCB',
    mono600: '#AFAFAF',
    mono700: '#757575',
    mono800: '#545454',
    mono900: '#333333',
    mono1000: '#000000',
    rating200: '#FFE3AC',
    rating400: '#FFC043',
    buttonPrimaryFill: '#000000',
    buttonPrimaryText: '#FFFFFF',
    buttonPrimaryHover: '#333333',
    buttonPrimaryActive: '#545454',
    buttonPrimarySelectedFill: '#545454',
    buttonPrimarySelectedText: '#FFFFFF',
    buttonPrimarySpinnerForeground: '#F6F6F6',
    buttonPrimarySpinnerBackground: '#757575',
    buttonSecondaryFill: '#EEEEEE',
    buttonSecondaryText: '#000000',
    buttonSecondaryHover: '#E2E2E2',
    buttonSecondaryActive: '#CBCBCB',
    buttonSecondarySelectedFill: '#CBCBCB',
    buttonSecondarySelectedText: '#000000',
    buttonSecondarySpinnerForeground: '#333333',
    buttonSecondarySpinnerBackground: '#CBCBCB',
    buttonTertiaryFill: 'transparent',
    buttonTertiaryText: '#000000',
    buttonTertiaryHover: '#F6F6F6',
    buttonTertiaryActive: '#EEEEEE',
    buttonTertiarySelectedFill: '#EEEEEE',
    buttonTertiarySelectedText: '#000000',
    buttonTertiarySpinnerForeground: '#333333',
    buttonTertiarySpinnerBackground: '#CBCBCB',
    buttonMinimalFill: 'transparent',
    buttonMinimalText: '#000000',
    buttonMinimalHover: '#F6F6F6',
    buttonMinimalActive: '#EEEEEE',
    buttonMinimalSelectedFill: '#EEEEEE',
    buttonMinimalSelectedText: '#000000',
    buttonMinimalSpinnerForeground: '#333333',
    buttonMinimalSpinnerBackground: '#CBCBCB',
    buttonDisabledFill: '#F6F6F6',
    buttonDisabledText: '#AFAFAF',
    buttonDisabledSpinnerForeground: '#AFAFAF',
    buttonDisabledSpinnerBackground: '#E2E2E2',
    breadcrumbsText: '#333333',
    breadcrumbsSeparatorFill: '#757575',
    datepickerBackground: '#FFFFFF',
    datepickerDayFont: '#000000',
    datepickerDayFontDisabled: '#CBCBCB',
    datepickerDayPseudoSelected: '#EEEEEE',
    datepickerDayPseudoHighlighted: '#E2E2E2',
    calendarBackground: '#FFFFFF',
    calendarForeground: '#000000',
    calendarForegroundDisabled: '#CBCBCB',
    calendarHeaderBackground: '#000000',
    calendarHeaderForeground: '#FFFFFF',
    calendarHeaderBackgroundActive: '#333333',
    calendarHeaderForegroundDisabled: '#757575',
    calendarDayBackgroundPseudoSelected: '#EEEEEE',
    calendarDayForegroundPseudoSelected: '#000000',
    calendarDayBackgroundPseudoSelectedHighlighted: '#E2E2E2',
    calendarDayForegroundPseudoSelectedHighlighted: '#000000',
    calendarDayBackgroundSelected: '#FFFFFF',
    calendarDayForegroundSelected: '#000000',
    calendarDayBackgroundSelectedHighlighted: '#000000',
    calendarDayForegroundSelectedHighlighted: '#FFFFFF',
    comboboxListItemFocus: '#F6F6F6',
    comboboxListItemHover: '#EEEEEE',
    fileUploaderBackgroundColor: '#F6F6F6',
    fileUploaderBackgroundColorActive: '#F6F6F6',
    fileUploaderBorderColorActive: '#000000',
    fileUploaderBorderColorDefault: '#CBCBCB',
    fileUploaderMessageColor: '#545454',
    linkText: '#000000',
    linkVisited: '#333333',
    linkHover: '#545454',
    linkActive: '#757575',
    listHeaderFill: '#FFFFFF',
    listBodyFill: '#F6F6F6',
    listIconFill: '#CBCBCB',
    listBorder: '#CBCBCB',
    progressStepsCompletedText: '#FFFFFF',
    progressStepsCompletedFill: '#000000',
    progressStepsActiveText: '#FFFFFF',
    progressStepsActiveFill: '#000000',
    progressStepsIconActiveFill: '#000000',
    toggleFill: '#FFFFFF',
    toggleFillChecked: '#000000',
    toggleFillDisabled: '#AFAFAF',
    toggleTrackFill: '#E2E2E2',
    toggleTrackFillDisabled: '#EEEEEE',
    tickFill: '#FFFFFF',
    tickFillHover: '#F6F6F6',
    tickFillActive: '#EEEEEE',
    tickFillSelected: '#000000',
    tickFillSelectedHover: '#333333',
    tickFillSelectedHoverActive: '#545454',
    tickFillError: '#FFEFED',
    tickFillErrorHover: '#FED7D2',
    tickFillErrorHoverActive: '#F1998E',
    tickFillErrorSelected: '#E11900',
    tickFillErrorSelectedHover: '#AB1300',
    tickFillErrorSelectedHoverActive: '#870F00',
    tickFillDisabled: '#AFAFAF',
    tickBorder: '#757575',
    tickBorderError: '#E11900',
    tickMarkFill: '#FFFFFF',
    tickMarkFillError: '#FFFFFF',
    tickMarkFillDisabled: '#FFFFFF',
    sliderTrackFill: '#E2E2E2',
    sliderTrackFillHover: '#CBCBCB',
    sliderTrackFillActive: '#AFAFAF',
    sliderTrackFillSelected: '#000000',
    sliderTrackFillSelectedHover: '#000000',
    sliderTrackFillSelectedActive: '#757575',
    sliderTrackFillDisabled: '#EEEEEE',
    sliderHandleFill: '#FFFFFF',
    sliderHandleFillHover: '#FFFFFF',
    sliderHandleFillActive: '#FFFFFF',
    sliderHandleFillSelected: '#FFFFFF',
    sliderHandleFillSelectedHover: '#FFFFFF',
    sliderHandleFillSelectedActive: '#FFFFFF',
    sliderHandleFillDisabled: '#CBCBCB',
    sliderHandleInnerFill: '#E2E2E2',
    sliderHandleInnerFillDisabled: '#E2E2E2',
    sliderHandleInnerFillSelectedHover: '#000000',
    sliderHandleInnerFillSelectedActive: '#757575',
    sliderBorder: '#CBCBCB',
    sliderBorderHover: '#000000',
    sliderBorderDisabled: '#AFAFAF',
    inputBorder: '#EEEEEE',
    inputFill: '#EEEEEE',
    inputFillError: '#FFEFED',
    inputFillDisabled: '#F6F6F6',
    inputFillActive: '#F6F6F6',
    inputFillPositive: '#E6F2ED',
    inputTextDisabled: '#AFAFAF',
    inputBorderError: '#F1998E',
    inputBorderPositive: '#66D19E',
    inputEnhancerFill: '#EEEEEE',
    inputEnhancerFillDisabled: '#EEEEEE',
    inputEnhancerTextDisabled: '#AFAFAF',
    inputPlaceholder: '#757575',
    inputPlaceholderDisabled: '#AFAFAF',
    menuFill: '#FFFFFF',
    menuFillHover: '#F6F6F6',
    menuFontDefault: '#545454',
    menuFontDisabled: '#CBCBCB',
    menuFontHighlighted: '#000000',
    menuFontSelected: '#000000',
    modalCloseColor: '#000000',
    modalCloseColorHover: '#545454',
    modalCloseColorFocus: '#545454',
    paginationTriangleDown: '#545454',
    headerNavigationFill: 'transparent',
    tabBarFill: '#F6F6F6',
    tabColor: '#545454',
    notificationPrimaryBackground: '#F6F6F6',
    notificationPrimaryText: '#757575',
    notificationInfoBackground: '#EFF3FE',
    notificationInfoText: '#1E54B7',
    notificationPositiveBackground: '#E6F2ED',
    notificationPositiveText: '#03703C',
    notificationWarningBackground: '#FFFAF0',
    notificationWarningText: '#BC8B2C',
    notificationNegativeBackground: '#FFEFED',
    notificationNegativeText: '#AB1300',
    tagFontDisabledRampUnit: '100',
    tagOutlinedDisabledRampUnit: '200',
    tagSolidFontRampUnit: '0',
    tagSolidRampUnit: '400',
    tagOutlinedFontRampUnit: '400',
    tagOutlinedRampUnit: '200',
    tagSolidHoverRampUnit: '50',
    tagSolidActiveRampUnit: '100',
    tagSolidDisabledRampUnit: '50',
    tagSolidFontHoverRampUnit: '500',
    tagLightRampUnit: '50',
    tagLightHoverRampUnit: '100',
    tagLightActiveRampUnit: '100',
    tagLightDisabledRampUnit: '50',
    tagLightFontRampUnit: '500',
    tagLightFontHoverRampUnit: '500',
    tagOutlinedHoverRampUnit: '50',
    tagOutlinedActiveRampUnit: '0',
    tagOutlinedFontHoverRampUnit: '400',
    tagNeutralFontDisabled: '#AFAFAF',
    tagNeutralOutlinedDisabled: '#E2E2E2',
    tagNeutralSolidFont: '#FFFFFF',
    tagNeutralSolidBackground: '#000000',
    tagNeutralOutlinedBackground: '#AFAFAF',
    tagNeutralOutlinedFont: '#000000',
    tagNeutralSolidHover: '#EEEEEE',
    tagNeutralSolidActive: '#E2E2E2',
    tagNeutralSolidDisabled: '#F6F6F6',
    tagNeutralSolidFontHover: '#333333',
    tagNeutralLightBackground: '#EEEEEE',
    tagNeutralLightHover: '#EEEEEE',
    tagNeutralLightActive: '#E2E2E2',
    tagNeutralLightDisabled: '#F6F6F6',
    tagNeutralLightFont: '#333333',
    tagNeutralLightFontHover: '#333333',
    tagNeutralOutlinedActive: '#333333',
    tagNeutralOutlinedFontHover: '#545454',
    tagNeutralOutlinedHover: 'rgba(0, 0, 0, 0.08)',
    tagPrimaryFontDisabled: '#AFAFAF',
    tagPrimaryOutlinedDisabled: '#E2E2E2',
    tagPrimarySolidFont: '#FFFFFF',
    tagPrimarySolidBackground: '#000000',
    tagPrimaryOutlinedFontHover: '#000000',
    tagPrimaryOutlinedFont: '#000000',
    tagPrimarySolidHover: '#EEEEEE',
    tagPrimarySolidActive: '#E2E2E2',
    tagPrimarySolidDisabled: '#F6F6F6',
    tagPrimarySolidFontHover: '#333333',
    tagPrimaryLightBackground: '#F6F6F6',
    tagPrimaryLightHover: '#EEEEEE',
    tagPrimaryLightActive: '#EEEEEE',
    tagPrimaryLightDisabled: '#F6F6F6',
    tagPrimaryLightFont: '#757575',
    tagPrimaryLightFontHover: '#757575',
    tagPrimaryOutlinedActive: '#545454',
    tagPrimaryOutlinedHover: 'rgba(0, 0, 0, 0.08)',
    tagPrimaryOutlinedBackground: '#AFAFAF',
    tagAccentFontDisabled: '#A0BFF8',
    tagAccentOutlinedDisabled: '#A0BFF8',
    tagAccentSolidFont: '#FFFFFF',
    tagAccentSolidBackground: '#276EF1',
    tagAccentOutlinedBackground: '#A0BFF8',
    tagAccentOutlinedFont: '#276EF1',
    tagAccentSolidHover: '#EFF3FE',
    tagAccentSolidActive: '#D4E2FC',
    tagAccentSolidDisabled: '#EFF3FE',
    tagAccentSolidFontHover: '#1E54B7',
    tagAccentLightBackground: '#EFF3FE',
    tagAccentLightHover: '#D4E2FC',
    tagAccentLightActive: '#D4E2FC',
    tagAccentLightDisabled: '#EFF3FE',
    tagAccentLightFont: '#1E54B7',
    tagAccentLightFontHover: '#1E54B7',
    tagAccentOutlinedActive: '#174291',
    tagAccentOutlinedFontHover: '#276EF1',
    tagAccentOutlinedHover: 'rgba(0, 0, 0, 0.08)',
    tagPositiveFontDisabled: '#66D19E',
    tagPositiveOutlinedDisabled: '#66D19E',
    tagPositiveSolidFont: '#FFFFFF',
    tagPositiveSolidBackground: '#05944F',
    tagPositiveOutlinedBackground: '#66D19E',
    tagPositiveOutlinedFont: '#05944F',
    tagPositiveSolidHover: '#E6F2ED',
    tagPositiveSolidActive: '#ADDEC9',
    tagPositiveSolidDisabled: '#E6F2ED',
    tagPositiveSolidFontHover: '#03703C',
    tagPositiveLightBackground: '#E6F2ED',
    tagPositiveLightHover: '#ADDEC9',
    tagPositiveLightActive: '#ADDEC9',
    tagPositiveLightDisabled: '#E6F2ED',
    tagPositiveLightFont: '#03703C',
    tagPositiveLightFontHover: '#03703C',
    tagPositiveOutlinedActive: '#03582F',
    tagPositiveOutlinedFontHover: '#05944F',
    tagPositiveOutlinedHover: 'rgba(0, 0, 0, 0.08)',
    tagWarningFontDisabled: '#FFCF70',
    tagWarningOutlinedDisabled: '#FFCF70',
    tagWarningSolidFont: '#674D1B',
    tagWarningSolidBackground: '#FFC043',
    tagWarningOutlinedBackground: '#FFCF70',
    tagWarningOutlinedFont: '#997328',
    tagWarningSolidHover: '#FFFAF0',
    tagWarningSolidActive: '#FFF2D9',
    tagWarningSolidDisabled: '#FFFAF0',
    tagWarningSolidFontHover: '#BC8B2C',
    tagWarningLightBackground: '#FFFAF0',
    tagWarningLightHover: '#FFF2D9',
    tagWarningLightActive: '#FFF2D9',
    tagWarningLightDisabled: '#FFFAF0',
    tagWarningLightFont: '#BC8B2C',
    tagWarningLightFontHover: '#BC8B2C',
    tagWarningOutlinedActive: '#997328',
    tagWarningOutlinedFontHover: '#997328',
    tagWarningOutlinedHover: 'rgba(0, 0, 0, 0.08)',
    tagNegativeFontDisabled: '#F1998E',
    tagNegativeOutlinedDisabled: '#F1998E',
    tagNegativeSolidFont: '#FFFFFF',
    tagNegativeSolidBackground: '#E11900',
    tagNegativeOutlinedBackground: '#F1998E',
    tagNegativeOutlinedFont: '#E11900',
    tagNegativeSolidHover: '#FFEFED',
    tagNegativeSolidActive: '#FED7D2',
    tagNegativeSolidDisabled: '#FFEFED',
    tagNegativeSolidFontHover: '#AB1300',
    tagNegativeLightBackground: '#FFEFED',
    tagNegativeLightHover: '#FED7D2',
    tagNegativeLightActive: '#FED7D2',
    tagNegativeLightDisabled: '#FFEFED',
    tagNegativeLightFont: '#AB1300',
    tagNegativeLightFontHover: '#AB1300',
    tagNegativeOutlinedActive: '#870F00',
    tagNegativeOutlinedFontHover: '#E11900',
    tagNegativeOutlinedHover: 'rgba(0, 0, 0, 0.08)',
    tableHeadBackgroundColor: '#FFFFFF',
    tableBackground: '#FFFFFF',
    tableStripedBackground: '#F6F6F6',
    tableFilter: '#AFAFAF',
    tableFilterHeading: '#757575',
    tableFilterBackground: '#FFFFFF',
    tableFilterFooterBackground: '#F6F6F6',
    toastText: '#FFFFFF',
    toastPrimaryBackground: '#757575',
    toastInfoBackground: '#1E54B7',
    toastPositiveBackground: '#03703C',
    toastWarningBackground: '#BC8B2C',
    toastNegativeBackground: '#AB1300',
    spinnerTrackFill: '#333333',
    progressbarTrackFill: '#333333',
    tooltipBackground: '#333333',
    tooltipText: '#FFFFFF',
    colorPrimary: '#000000',
    colorSecondary: '#545454',
    background: '#FFFFFF',
    backgroundAlt: '#FFFFFF',
    backgroundInv: '#000000',
    foreground: '#000000',
    foregroundAlt: '#545454',
    foregroundInv: '#FFFFFF',
    border: '#CBCBCB',
    borderAlt: '#AFAFAF',
    borderFocus: '#000000',
    borderError: '#E11900',
    shadowFocus: 'rgba(39, 110, 241, 0.32)',
    shadowError: 'rgba(229, 73, 55, 0.32)',
    backgroundPrimary: '#FFFFFF',
    backgroundSecondary: '#F6F6F6',
    backgroundTertiary: '#EEEEEE',
    backgroundInversePrimary: '#000000',
    backgroundInverseSecondary: '#1F1F1F',
    contentPrimary: '#000000',
    contentSecondary: '#545454',
    contentTertiary: '#757575',
    contentInversePrimary: '#FFFFFF',
    contentInverseSecondary: '#CBCBCB',
    contentInverseTertiary: '#AFAFAF',
    borderOpaque: '#E2E2E2',
    borderTransparent: 'rgba(0, 0, 0, 0.08)',
    borderSelected: '#000000',
    borderInverseOpaque: '#333333',
    borderInverseTransparent: 'rgba(255, 255, 255, 0.2)',
    borderInverseSelected: '#FFFFFF',
    backgroundStateDisabled: '#F6F6F6',
    backgroundOverlayDark: 'rgba(0, 0, 0, 0.3)',
    backgroundOverlayLight: 'rgba(0, 0, 0, 0.08)',
    backgroundAccent: '#276EF1',
    backgroundNegative: '#E11900',
    backgroundWarning: '#FFC043',
    backgroundPositive: '#05944F',
    backgroundLightAccent: '#EFF3FE',
    backgroundLightNegative: '#FFEFED',
    backgroundLightWarning: '#FFFAF0',
    backgroundLightPositive: '#E6F2ED',
    backgroundAlwaysDark: '#000000',
    backgroundAlwaysLight: '#FFFFFF',
    contentStateDisabled: '#AFAFAF',
    contentAccent: '#276EF1',
    contentOnColor: '#FFFFFF',
    contentOnColorInverse: '#000000',
    contentNegative: '#E11900',
    contentWarning: '#BC8B2C',
    contentPositive: '#05944F',
    borderStateDisabled: '#F6F6F6',
    borderAccent: '#276EF1',
    borderAccentLight: '#A0BFF8',
    borderNegative: '#F1998E',
    borderWarning: '#FFE3AC',
    borderPositive: '#66D19E',
  },
  animation: {
    timing100: '100ms',
    timing200: '200ms',
    timing300: '300ms',
    timing400: '400ms',
    timing500: '500ms',
    timing600: '600ms',
    timing700: '700ms',
    timing800: '800ms',
    timing900: '900ms',
    timing1000: '1000ms',
    easeInCurve: 'cubic-bezier(.8, .2, .6, 1)',
    easeOutCurve: 'cubic-bezier(.2, .8, .4, 1)',
    easeInOutCurve: 'cubic-bezier(0.4, 0, 0.2, 1)',
    easeInQuinticCurve: 'cubic-bezier(0.755, 0.05, 0.855, 0.06)',
    easeOutQuinticCurve: 'cubic-bezier(0.23, 1, 0.32, 1)',
    easeInOutQuinticCurve: 'cubic-bezier(0.86, 0, 0.07, 1)',
    linearCurve: 'cubic-bezier(0, 0, 1, 1)',
  },
  breakpoints: { small: 320, medium: 600, large: 1136 },
  borders: {
    border100: {
      borderColor: 'hsla(0, 0%, 0%, 0.04)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    border200: {
      borderColor: 'hsla(0, 0%, 0%, 0.08)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    border300: {
      borderColor: 'hsla(0, 0%, 0%, 0.12)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    border400: {
      borderColor: 'hsla(0, 0%, 0%, 0.16)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    border500: {
      borderColor: 'hsla(0, 0%, 0%, 0.2)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    border600: {
      borderColor: 'hsla(0, 0%, 0%, 0.24)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    radius100: '2px',
    radius200: '4px',
    radius300: '8px',
    radius400: '12px',
    useRoundedCorners: true,
    buttonBorderRadius: '0px',
    inputBorderRadius: '0px',
    popoverBorderRadius: '0px',
    surfaceBorderRadius: '0px',
  },
  direction: 'auto',
  grid: {
    columns: [4, 8, 12],
    gutters: [16, 36, 36],
    margins: [16, 36, 64],
    gaps: 0,
    unit: 'px',
    maxWidth: 1280,
  },
  lighting: {
    shadow400: '0 1px 4px hsla(0, 0%, 0%, 0.16)',
    shadow500: '0 2px 8px hsla(0, 0%, 0%, 0.16)',
    shadow600: '0 4px 16px hsla(0, 0%, 0%, 0.16)',
    shadow700: '0 8px 24px hsla(0, 0%, 0%, 0.16)',
    overlay0: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0)',
    overlay100: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.04)',
    overlay200: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.08)',
    overlay300: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.12)',
    overlay400: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.16)',
    overlay500: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.2)',
    overlay600: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.24)',
  },
  mediaQuery: {
    small: '@media screen and (min-width: 320px)',
    medium: '@media screen and (min-width: 600px)',
    large: '@media screen and (min-width: 1136px)',
  },
  sizing: {
    scale0: '2px',
    scale100: '4px',
    scale200: '6px',
    scale300: '8px',
    scale400: '10px',
    scale500: '12px',
    scale550: '14px',
    scale600: '16px',
    scale650: '18px',
    scale700: '20px',
    scale750: '22px',
    scale800: '24px',
    scale850: '28px',
    scale900: '32px',
    scale950: '36px',
    scale1000: '40px',
    scale1200: '48px',
    scale1400: '56px',
    scale1600: '64px',
    scale2400: '96px',
    scale3200: '128px',
    scale4800: '192px',
  },
  typography: {
    font100: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '12px',
      fontWeight: 'normal',
      lineHeight: '20px',
    },
    font150: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '12px',
      fontWeight: 500,
      lineHeight: '16px',
    },
    font200: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '14px',
      fontWeight: 'normal',
      lineHeight: '20px',
    },
    font250: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '14px',
      fontWeight: 500,
      lineHeight: '16px',
    },
    font300: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '16px',
      fontWeight: 'normal',
      lineHeight: '24px',
    },
    font350: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '16px',
      fontWeight: 500,
      lineHeight: '20px',
    },
    font400: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '18px',
      fontWeight: 'normal',
      lineHeight: '28px',
    },
    font450: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '18px',
      fontWeight: 500,
      lineHeight: '24px',
    },
    font550: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '20px',
      fontWeight: 500,
      lineHeight: '28px',
    },
    font650: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '24px',
      fontWeight: 500,
      lineHeight: '32px',
    },
    font750: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '28px',
      fontWeight: 500,
      lineHeight: '36px',
    },
    font850: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '32px',
      fontWeight: 500,
      lineHeight: '40px',
    },
    font950: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '36px',
      fontWeight: 500,
      lineHeight: '44px',
    },
    font1050: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '40px',
      fontWeight: 500,
      lineHeight: '52px',
    },
    font1150: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '36px',
      fontWeight: 500,
      lineHeight: '44px',
    },
    font1250: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '44px',
      fontWeight: 500,
      lineHeight: '52px',
    },
    font1350: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '52px',
      fontWeight: 500,
      lineHeight: '64px',
    },
    font1450: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '96px',
      fontWeight: 500,
      lineHeight: '112px',
    },
    MonoParagraphXSmall: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '12px',
      fontWeight: 'normal',
      lineHeight: '20px',
    },
    MonoParagraphSmall: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '14px',
      fontWeight: 'normal',
      lineHeight: '20px',
    },
    MonoParagraphMedium: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '16px',
      fontWeight: 'normal',
      lineHeight: '24px',
    },
    MonoParagraphLarge: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '18px',
      fontWeight: 'normal',
      lineHeight: '28px',
    },
    MonoLabelXSmall: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '12px',
      fontWeight: 500,
      lineHeight: '16px',
    },
    MonoLabelSmall: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '14px',
      fontWeight: 500,
      lineHeight: '16px',
    },
    MonoLabelMedium: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '16px',
      fontWeight: 500,
      lineHeight: '20px',
    },
    MonoLabelLarge: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '18px',
      fontWeight: 500,
      lineHeight: '24px',
    },
    MonoHeadingXSmall: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '20px',
      fontWeight: 500,
      lineHeight: '28px',
    },
    MonoHeadingSmall: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '24px',
      fontWeight: 500,
      lineHeight: '32px',
    },
    MonoHeadingMedium: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '28px',
      fontWeight: 500,
      lineHeight: '36px',
    },
    MonoHeadingLarge: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '32px',
      fontWeight: 500,
      lineHeight: '40px',
    },
    MonoHeadingXLarge: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '36px',
      fontWeight: 500,
      lineHeight: '44px',
    },
    MonoHeadingXXLarge: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '40px',
      fontWeight: 500,
      lineHeight: '52px',
    },
    MonoDisplayXSmall: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '36px',
      fontWeight: 500,
      lineHeight: '44px',
    },
    MonoDisplaySmall: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '44px',
      fontWeight: 500,
      lineHeight: '52px',
    },
    MonoDisplayMedium: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '52px',
      fontWeight: 500,
      lineHeight: '64px',
    },
    MonoDisplayLarge: {
      fontFamily: '"Lucida Console", Monaco, monospace',
      fontSize: '96px',
      fontWeight: 500,
      lineHeight: '112px',
    },
  },
  zIndex: { modal: 2000 },
};
